sudo: false
language: node_js

node_js:
  - "5"
  - "6"

services:
  - mongodb

env:
  - CXX=g++=4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

after_success:
   - npm run coveralls


deploy:
  provider: codedeploy
  access_key_id: AKIAI4C7YLG342MK6KMA
  secret_access_key: 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
  bucket: 'hive-backend-dev-bucket'
  deployment-group: 'HiveBackendTeam'
